spring.application.name=riesgos
# Conexión a la Base de Datos SQL Server Express
spring.datasource.url=jdbc:sqlserver://LAP-GIOVANNI-GA;databaseName=BancoRiesgos;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Autenticación de Windows (Integrated Security)
spring.datasource.integratedSecurity=true

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
